In [7]:
import numpy as np
import os
import csv
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import pearsonr
import multiprocessing as mp
from oucorr import calcCorr, calcSingleCorr
import itertools
import glob


SMALL_SIZE = 16
MEDIUM_SIZE = 18
BIGGER_SIZE = 20

plt.rc('font', size=SMALL_SIZE)          # controls default text sizes
plt.rc('axes', titlesize=SMALL_SIZE)     # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title

SEED = 350107321 # from random.org
np.random.seed(SEED)

print(plt.style.available)
plt.style.use('seaborn-white')

['Solarize_Light2', '_classic_test_patch', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark', 'seaborn-dark-palette', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'tableau-colorblind10']


In [3]:
N = 720
REGIONS = 498

In [2]:
filelist = glob.glob("time_series/*.csv")
filelist

['time_series/sub-056_ses-glc_task-task_run-2.csv',
 'time_series/sub-027_ses-glc_task-rest_run-2.csv',
 'time_series/sub-057_ses-bhb_task-rest_run-1.csv',
 'time_series/sub-060_ses-glc_task-rest_run-2.csv',
 'time_series/sub-010_ses-bhb_task-rest_run-1.csv',
 'time_series/sub-061_ses-bhb_task-task_run-1.csv',
 'time_series/sub-080_ses-glc_task-rest_run-2.csv',
 'time_series/sub-015_ses-bhb_task-rest_run-2.csv',
 'time_series/sub-084_ses-bhb_task-task_run-2.csv',
 'time_series/sub-064_ses-bhb_task-task_run-2.csv',
 'time_series/sub-085_ses-glc_task-rest_run-1.csv',
 'time_series/sub-053_ses-glc_task-task_run-1.csv',
 'time_series/sub-049_ses-glc_task-rest_run-2.csv',
 'time_series/sub-023_ses-bhb_task-task_run-2.csv',
 'time_series/sub-052_ses-bhb_task-rest_run-2.csv',
 'time_series/sub-048_ses-bhb_task-task_run-1.csv',
 'time_series/sub-041_ses-bhb_task-rest_run-1.csv',
 'time_series/sub-076_ses-glc_task-rest_run-2.csv',
 'time_series/sub-006_ses-bhb_task-rest_run-1.csv',
 'time_serie

In [9]:
for f in filelist:
    roi_time_series = pd.read_csv(f,header=None, index_col=False)
    roi_time_series = np.array(roi_time_series)
    f_out_back = f[f.find("/"):]
    f_out = "results/connectivity"+f_out_back[:f_out_back.find(".")] + "_CdCB"
    # Convert into numpy array
    C,dC,B1 = calcSingleCorr(roi_time_series,N,REGIONS)
    np.savez(f_out, C=C, dC=dC, B=B1)
    print(f_out)

results/connectivity/sub-056_ses-glc_task-task_run-2_CdCB


KeyboardInterrupt: 

In [10]:
C

array([[ 1.        ,  5.25657805,  0.49585749, ...,  1.08523216,
         0.94045978,  1.03518095],
       [ 5.25657805,  1.        ,  0.40935255, ...,  1.89780353,
         1.10651582,  1.17204378],
       [ 0.49585749,  0.40935255,  1.        , ...,  0.96588626,
        -0.51495409,  0.03542739],
       ...,
       [ 1.08523216,  1.89780353,  0.96588626, ...,  1.        ,
         0.91924919,  1.80955718],
       [ 0.94045978,  1.10651582, -0.51495409, ...,  0.91924919,
         1.        ,  2.09101342],
       [ 1.03518095,  1.17204378,  0.03542739, ...,  1.80955718,
         2.09101342,  1.        ]])

In [11]:
dC

array([[0.        , 1.55655336, 0.45944946, ..., 0.5556906 , 0.56768728,
        0.59102822],
       [1.55655336, 0.        , 0.4502891 , ..., 0.74523179, 0.6075041 ,
        0.64967483],
       [0.45944946, 0.4502891 , 0.        , ..., 0.55705342, 0.55441833,
        0.37836431],
       ...,
       [0.5556906 , 0.74523179, 0.55705342, ..., 0.        , 0.51264238,
        0.74583084],
       [0.56768728, 0.6075041 , 0.55441833, ..., 0.51264238, 0.        ,
        0.8148116 ],
       [0.59102822, 0.64967483, 0.37836431, ..., 0.74583084, 0.8148116 ,
        0.        ]])

In [12]:
B1

array([[0.9655497 , 0.96787403, 0.96982657, ..., 0.96446765, 0.96413565,
        0.96633683],
       [0.96787403, 0.96725413, 0.97097204, ..., 0.96361668, 0.9654006 ,
        0.9656079 ],
       [0.96982657, 0.97097204, 0.96208119, ..., 0.95825373, 0.9627648 ,
        0.96130858],
       ...,
       [0.96446765, 0.96361668, 0.95825373, ..., 0.95583581, 0.96210338,
        0.9601821 ],
       [0.96413565, 0.9654006 , 0.9627648 , ..., 0.96210338, 0.96110285,
        0.96363957],
       [0.96633683, 0.9656079 , 0.96130858, ..., 0.9601821 , 0.96363957,
        0.96383225]])